{% set version = "5.0.1" %}

package:
  name: edffile
  version: {{ version }}

source:
  path: src

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=2.7,<4
    - pip
    - numpy
  run:
    - python >=2.7,<4
    - numpy

test:
  imports:
    - EdfFile

about:
  # Long term goal is to have the src/ folder in this recipe as a stand-alone
  # project on github. This file is part of another, much larger project. It
  # is broken out so that users do not have to install a full GUI simply to
  # get Edf file format I/O.
  home: https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaIO/EdfFile.py
  license: MIT
  summary: 'Reader for EDF files part of the PyMCA x-ray fluorescence toolkit'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - licode
    - ravescovi
    - tacaswell
